version: "3.9"  # Use the latest Compose file format version

services:
  web:
    image: php:8.2-apache  # Use PHP with Apache preconfigured
    container_name: php-app
    volumes:
      - ./app:/var/www/html  # Mount the 'app' directory into the container
    ports:
      - "80:80"  # Map port 8080 on the host to port 80 in the container
